version: "3.1"

services:
  mysql:
    image: mysql:latest
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    container_name: mysql_db
    ports:
      - "3308:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_password
      MYSQL_DATABASE: doarmais
    secrets:
      - db_password
    networks:
      - spring-mysql
secrets:
  db_password:
    file: ./database/secrets/secret.txt

networks:
  spring-mysql:
